use super::text_key::TextKey;
use crate::resource::*;

pub fn resource(id: u32) -> &'static str {
    match id {
        IDS_PERFPAGETITLE => "Leistung",
        IDS_NETPAGETITLE => "Netzwerk",
        IDS_RUNTITLE => "Ausführen",
        IDS_RUNTEXT => "Geben Sie den Namen eines Programms, Ordners, Dokuments oder einer Internetressource ein, und Windows wird es für Sie öffnen.",
        IDS_APPTITLE | IDS_TASKMGR => "Windows NT Task-Manager",
        IDS_PROCPAGETITLE => "Prozesse",
        IDS_TASKPAGETITLE => "Anwendungen",
        IDS_USERPAGETITLE => "Benutzer",
        IDS_TASKMGRDISABLED => "Der Task-Manager wurde durch den Administrator deaktiviert.",
        IDS_WARNING => "Task-Manager-Warnung",
        IDS_LOW => "Niedrig",
        IDS_HIGH => "Hoch",
        IDS_REALTIME => "Echtzeit",
        IDS_NORMAL => "Normal",
        IDS_UNKNOWN => "Unbekannt",
        IDS_CANTSETAFFINITY => "Der Vorgang konnte nicht abgeschlossen werden.\n\n",
        IDS_CANTKILL => "Prozess konnte nicht beendet werden",
        IDS_CANTDEBUG => "Debugger konnte nicht angefügt werden",
        IDS_CANTCHANGEPRI => "Priorität konnte nicht geändert werden",
        IDS_FMTTASKS => "Anwendungen: %d",
        IDS_FMTPROCS => "Prozesse: %d",
        IDS_FMTCPU => "CPU-Auslastung: %d%%",
        IDS_FMTMEM => "Speicherauslastung: %dK / %dK",
        IDS_INVALIDOPTION => "Ungültige Option",
        IDS_NOAFFINITYMASK => "Der Prozess muss mindestens einem Prozessor zugeordnet sein.",
        IDS_FMTCPUNUM => "CPU %d",
        IDS_TOTALTIME => "Gesamt-CPU",
        IDS_KERNELTIME => "Kernel-CPU",
        IDS_MEMUSAGE => "Speicherauslastung",
        IDS_COL_IMAGENAME => "Abbildname",
        IDS_COL_PID => "PID",
        IDS_COL_CPU => "CPU",
        IDS_COL_CPUTIME => "CPU-Zeit",
        IDS_COL_MEMUSAGE => "Speicherauslastung",
        IDS_COL_MEMUSAGEDIFF => "Speicherdelta",
        IDS_COL_PAGEFAULTS => "Seitenfehler",
        IDS_COL_PAGEFAULTSDIFF => "PF-Delta",
        IDS_COL_COMMITCHARGE => "VM-Groesse",
        IDS_COL_PAGEDPOOL => "Ausgelagerter Pool",
        IDS_COL_NONPAGEDPOOL => "Nicht ausgelagerter Pool",
        IDS_COL_BASEPRIORITY => "Basisprioritaet",
        IDS_COL_HANDLECOUNT => "Handles",
        IDS_COL_THREADCOUNT => "Threads",
        IDS_COL_SESSIONID => "Sitzungs-ID",
        IDS_COL_USERNAME => "Benutzername",
        IDS_COL_TASKNAME => "Task",
        IDS_COL_TASKSTATUS => "Status",
        IDS_COL_TASKWINSTATION => "Fensterstation",
        IDS_COL_TASKDESKTOP => "Desktop",
        IDS_PRICHANGE => {
            "WARNUNG: Das Ändern der Prioritätsklasse dieses Prozesses kann unerwünschte Folgen bis hin zur Systeminstabilität haben. Möchten Sie die Prioritätsklasse wirklich ändern?"
        }
        IDS_KILL => {
            "WARNUNG: Das Beenden eines Prozesses kann unerwünschte Folgen einschließlich Datenverlust und Systeminstabilität haben. Der Prozess kann seinen Zustand oder Daten vor dem Beenden nicht speichern. Möchten Sie den Prozess wirklich beenden?"
        }
        IDS_DEBUG => {
            "WARNUNG: Das Debuggen dieses Prozesses kann zu Datenverlust führen. Möchten Sie den Debugger wirklich anhängen?"
        }
        _ => "",
    }
}

pub fn text(key: TextKey) -> &'static str {
    match key {
        TextKey::File => "&Datei",
        TextKey::Options => "&Optionen",
        TextKey::View => "&Ansicht",
        TextKey::Windows => "&Fenster",
        TextKey::Help => "&Hilfe",
        TextKey::UpdateSpeed => "&Aktualisierungsgeschwindigkeit",
        TextKey::CpuHistory => "&CPU-Verlauf",
        TextKey::SelectColumnsMenu => "Spalten auswaehlen...",
        TextKey::SelectColumnsTitle => "Spalten auswaehlen",
        TextKey::SelectProcessColumnsDescription => {
            "Waehlen Sie die Spalten aus, die auf der Prozessseite des Task-Managers angezeigt werden sollen."
        }
        TextKey::NewTaskMenu | TextKey::NewTaskButton => "&Ausführen...",
        TextKey::ExitTaskManager => "Task-Manager be&enden",
        TextKey::AlwaysOnTop => "&Immer im Vordergrund",
        TextKey::MinimizeOnUse => "Nach Verwendung &minimieren",
        TextKey::Confirmations => "&Bestaetigungen",
        TextKey::HideWhenMinimized => "Beim Minimieren &ausblenden",
        TextKey::RefreshNow => "&Jetzt aktualisieren",
        TextKey::High => "&Hoch",
        TextKey::Normal => "&Normal",
        TextKey::Low => "&Niedrig",
        TextKey::Paused => "&Angehalten",
        TextKey::LargeIcons => "Gro&sse Symbole",
        TextKey::SmallIcons => "&Kleine Symbole",
        TextKey::Details => "&Details",
        TextKey::TileHorizontally => "Hori&zontal anordnen",
        TextKey::TileVertically => "&Vertikal anordnen",
        TextKey::Minimize => "&Minimieren",
        TextKey::Maximize => "Ma&ximieren",
        TextKey::Cascade => "&Ueberlappend",
        TextKey::BringToFront => "In den &Vordergrund",
        TextKey::HelpTopics => "Task-Manager-&Hilfethemen",
        TextKey::AboutTaskManager => "&Info zu Task-Manager",
        TextKey::OneGraphAllCpus => "Ein Diagramm, &alle CPUs",
        TextKey::OneGraphPerCpu => "Ein Diagramm &pro CPU",
        TextKey::ShowKernelTimes => "&Kernelzeiten anzeigen",
        TextKey::Show16BitTasks => "16-Bit-&Tasks anzeigen",
        TextKey::NoTitle => "&Kein Titel",
        TextKey::RestoreTaskManager => "Task-Manager &wiederherstellen",
        TextKey::SwitchTo => "&Wechseln zu",
        TextKey::EndTask => "Task &beenden",
        TextKey::EndProcess => "Prozess &beenden",
        TextKey::Debug => "&Debuggen",
        TextKey::SetPriority => "&Prioritaet festlegen",
        TextKey::Realtime => "&Echtzeit",
        TextKey::SetAffinity => "&Affinitaet festlegen...",
        TextKey::GoToProcess => "&Zum Prozess wechseln",
        TextKey::ShowFullAccountName => "Vollständigen Kontonamen anzeigen",
        TextKey::SendMessageTitle => "Nachricht senden",
        TextKey::MessageTitleLabel => "Nachrichtentitel:",
        TextKey::MessageLabel => "Nachricht:",
        TextKey::Disconnect => "&Trennen",
        TextKey::Logoff => "A&bmelden",
        TextKey::SendMessage => "&Nachricht senden...",
        TextKey::TaskManager => "Task-Manager",
        TextKey::Tasks => "Anwendungen",
        TextKey::Processes => "Prozesse",
        TextKey::Users => "Benutzer",
        TextKey::Handles => "Handles",
        TextKey::Threads => "Threads",
        TextKey::ProcessesLabel => "Prozesse",
        TextKey::User => "Benutzer",
        TextKey::Ok => "OK",
        TextKey::Cancel => "Abbrechen",
        TextKey::ImageName => "Abbildname",
        TextKey::PidProcessIdentifier => "PID (Prozesskennung)",
        TextKey::CpuUsage => "CPU-Auslastung",
        TextKey::CpuUsageHistory => "CPU-Auslastungsverlauf",
        TextKey::PhysicalMemoryK => "Physischer Speicher (K)",
        TextKey::CommitChargeK => "Zugesicherter Speicher (K)",
        TextKey::KernelMemoryK => "Kernelspeicher (K)",
        TextKey::Totals => "Summen",
        TextKey::Total => "Gesamt",
        TextKey::Available => "Verfuegbar",
        TextKey::FileCache => "Dateicache",
        TextKey::Paged => "Ausgelagert",
        TextKey::Nonpaged => "Nicht ausgelagert",
        TextKey::Limit => "Limit",
        TextKey::Peak => "Spitze",
        TextKey::UserName => "Benutzername",
        TextKey::SessionId => "Sitzungs-ID",
        TextKey::CpuTime => "CPU-Zeit",
        TextKey::MemoryUsage => "Speicherauslastung",
        TextKey::MemoryUsageDelta => "Aenderung der Speicherauslastung",
        TextKey::PageFaults => "Seitenfehler",
        TextKey::PageFaultsDelta => "Aenderung der Seitenfehler",
        TextKey::VirtualMemorySize => "Groesse des virtuellen Speichers",
        TextKey::PagedPool => "Ausgelagerter Pool",
        TextKey::NonPagedPool => "Nicht ausgelagerter Pool",
        TextKey::BasePriority => "Basisprioritaet",
        TextKey::HandleCount => "Handleanzahl",
        TextKey::ThreadCount => "Threadanzahl",
        TextKey::ProcessorAffinity => "Prozessoraffinitaet",
        TextKey::Processors => "Prozessoren",
        TextKey::ClientName => "Clientname",
        TextKey::Session => "Sitzung",
        TextKey::Status => "Status",
        TextKey::Bitness32Suffix => "(32-Bit)",
        TextKey::NotResponding => "Keine Rueckmeldung",
        TextKey::Running => "Wird ausgefuehrt",
        TextKey::MessageCouldNotBeSent => "Die Nachricht konnte nicht gesendet werden.",
        TextKey::ConfirmLogoffSelectedUsers => {
            "Moechten Sie die ausgewaehlten Benutzer wirklich abmelden?"
        }
        TextKey::ConfirmDisconnectSelectedUsers => {
            "Moechten Sie die ausgewaehlten Benutzer wirklich trennen?"
        }
        TextKey::SelectedUserCouldNotBeLoggedOff => {
            "Der ausgewaehlte Benutzer konnte nicht abgemeldet werden."
        }
        TextKey::SelectedUserCouldNotBeDisconnected => {
            "Der ausgewaehlte Benutzer konnte nicht getrennt werden."
        }
        TextKey::Win32ErrorPrefix => "Win32-Fehler:",
        TextKey::ProcessorAffinityDescription => {
            "Die Prozessoraffinität legt fest, auf welchen CPUs der Prozess ausgefuehrt werden darf."
        }
        TextKey::MemUsage => "Speicherauslastung",
        TextKey::MemoryUsageHistory => "Speicherauslastungsverlauf",
        TextKey::NoActiveNetworkAdaptersFound => "Keine aktiven Netzwerkadapter gefunden.",
        TextKey::Adapter => "Adapter",
        TextKey::NetworkUtilization => "Netzwerkauslastung",
        TextKey::LinkSpeed => "Verbindungsgeschwindigkeit",
        TextKey::State => "Status",
        TextKey::BytesSent => "Gesendete Bytes",
        TextKey::BytesReceived => "Empfangene Bytes",
        TextKey::BytesTotal => "Bytes gesamt",
        TextKey::Recv => "Empf.",
        TextKey::Sent => "Ges.",
        TextKey::Connected => "Verbunden",
        TextKey::Disconnected => "Getrennt",
        TextKey::Connecting => "Wird verbunden",
        TextKey::Disconnecting => "Wird getrennt",
        TextKey::HardwareMissing => "Hardware fehlt",
        TextKey::HardwareDisabled => "Hardware deaktiviert",
        TextKey::HardwareMalfunction => "Hardwarefehler",
        TextKey::Unknown => "Unbekannt",
        TextKey::Active => "Aktiv",
        TextKey::ConnectQuery => "Verbindungsabfrage",
        TextKey::Shadow => "Schatten",
        TextKey::Idle => "Leerlauf",
        TextKey::Listening => "Lauscht",
        TextKey::Reset => "Zuruecksetzen",
        TextKey::Down => "Inaktiv",
        TextKey::Init => "Initialisierung",
    }
}
