//! 西班牙语语言表。

use super::text_key::TextKey;
use crate::resource::*;

pub fn resource(id: u32) -> &'static str {
    match id {
        IDS_PERFPAGETITLE => "Rendimiento",
        IDS_NETPAGETITLE => "Red",
        IDS_RUNTITLE => "Ejecutar",
        IDS_RUNTEXT => "Escriba el nombre de un programa, carpeta, documento o recurso de Internet, y Windows lo abrirá por usted.",
        IDS_APPTITLE | IDS_TASKMGR => "Administrador de tareas de Windows NT",
        IDS_PROCPAGETITLE => "Procesos",
        IDS_TASKPAGETITLE => "Aplicaciones",
        IDS_USERPAGETITLE => "Usuarios",
        IDS_TASKMGRDISABLED => "El Administrador de tareas ha sido deshabilitado por su administrador.",
        IDS_WARNING => "Advertencia del Administrador de tareas",
        IDS_LOW => "Baja",
        IDS_HIGH => "Alta",
        IDS_REALTIME => "Tiempo real",
        IDS_NORMAL => "Normal",
        IDS_UNKNOWN => "Desconocido",
        IDS_CANTSETAFFINITY => "No se pudo completar la operación.\n\n",
        IDS_CANTKILL => "No se pudo finalizar el proceso",
        IDS_CANTDEBUG => "No se pudo adjuntar el depurador",
        IDS_CANTCHANGEPRI => "No se pudo cambiar la prioridad",
        IDS_FMTTASKS => "Aplicaciones: %d",
        IDS_FMTPROCS => "Procesos: %d",
        IDS_FMTCPU => "Uso de CPU: %d%%",
        IDS_FMTMEM => "Uso de memoria: %dK / %dK",
        IDS_INVALIDOPTION => "Opción no válida",
        IDS_NOAFFINITYMASK => "El proceso debe tener afinidad con al menos un procesador.",
        IDS_FMTCPUNUM => "CPU %d",
        IDS_TOTALTIME => "CPU total",
        IDS_KERNELTIME => "CPU del núcleo",
        IDS_MEMUSAGE => "Uso de memoria",
        IDS_COL_IMAGENAME => "Nombre de imagen",
        IDS_COL_PID => "PID",
        IDS_COL_CPU => "CPU",
        IDS_COL_CPUTIME => "Tiempo de CPU",
        IDS_COL_MEMUSAGE => "Uso de memoria",
        IDS_COL_MEMUSAGEDIFF => "Delta de memoria",
        IDS_COL_PAGEFAULTS => "Errores de página",
        IDS_COL_PAGEFAULTSDIFF => "Delta de errores de página",
        IDS_COL_COMMITCHARGE => "Tamaño de memoria virtual",
        IDS_COL_PAGEDPOOL => "Bloque paginado",
        IDS_COL_NONPAGEDPOOL => "Bloque no paginado",
        IDS_COL_BASEPRIORITY => "Prioridad base",
        IDS_COL_HANDLECOUNT => "Handles",
        IDS_COL_THREADCOUNT => "Hilos",
        IDS_COL_SESSIONID => "Id. de sesión",
        IDS_COL_USERNAME => "Nombre de usuario",
        IDS_COL_TASKNAME => "Tarea",
        IDS_COL_TASKSTATUS => "Estado",
        IDS_COL_TASKWINSTATION => "Estación Win",
        IDS_COL_TASKDESKTOP => "Escritorio",
        IDS_PRICHANGE => {
            "ADVERTENCIA: Cambiar la clase de prioridad de este proceso puede causar resultados no deseados, incluida la inestabilidad del sistema. ¿Seguro que desea cambiar la clase de prioridad?"
        }
        IDS_KILL => {
            "ADVERTENCIA: Finalizar un proceso puede causar resultados no deseados, incluida la pérdida de datos y la inestabilidad del sistema. El proceso no tendrá oportunidad de guardar su estado o sus datos antes de ser finalizado. ¿Seguro que desea finalizar este proceso?"
        }
        IDS_DEBUG => {
            "ADVERTENCIA: Depurar este proceso puede causar pérdida de datos. ¿Seguro que desea adjuntar el depurador?"
        }
        _ => "",
    }
}

pub fn text(key: TextKey) -> &'static str {
    match key {
        TextKey::File => "&Archivo",
        TextKey::Options => "&Opciones",
        TextKey::View => "&Ver",
        TextKey::Windows => "&Ventanas",
        TextKey::Help => "Ay&uda",
        TextKey::UpdateSpeed => "&Velocidad de actualización",
        TextKey::CpuHistory => "&Historial de CPU",
        TextKey::SelectColumnsMenu => "Seleccionar columnas...",
        TextKey::SelectColumnsTitle => "Seleccionar columnas",
        TextKey::SelectProcessColumnsDescription => {
            "Seleccione las columnas que aparecerán en la pestaña Procesos del Administrador de tareas."
        }
        TextKey::NewTaskMenu | TextKey::NewTaskButton => "&Ejecutar...",
        TextKey::ExitTaskManager => "&Salir del Administrador de tareas",
        TextKey::AlwaysOnTop => "&Siempre visible",
        TextKey::MinimizeOnUse => "&Minimizar al usar",
        TextKey::Confirmations => "&Confirmaciones",
        TextKey::HideWhenMinimized => "&Ocultar al minimizar",
        TextKey::RefreshNow => "&Actualizar ahora",
        TextKey::High => "&Alta",
        TextKey::Normal => "&Normal",
        TextKey::Low => "&Baja",
        TextKey::Paused => "&Pausado",
        TextKey::LargeIcons => "Iconos &grandes",
        TextKey::SmallIcons => "Iconos &pequeños",
        TextKey::Details => "&Detalles",
        TextKey::TileHorizontally => "Mosaico &horizontal",
        TextKey::TileVertically => "Mosaico &vertical",
        TextKey::Minimize => "&Minimizar",
        TextKey::Maximize => "Ma&ximizar",
        TextKey::Cascade => "&Cascada",
        TextKey::BringToFront => "Traer al &frente",
        TextKey::HelpTopics => "Temas de a&yuda del Administrador de tareas",
        TextKey::AboutTaskManager => "&Acerca del Administrador de tareas",
        TextKey::OneGraphAllCpus => "Un gráfico, &todas las CPU",
        TextKey::OneGraphPerCpu => "Un gráfico &por CPU",
        TextKey::ShowKernelTimes => "Mostrar tiempos del &núcleo",
        TextKey::NoTitle => "&Sin título",
        TextKey::RestoreTaskManager => "&Restaurar el Administrador de tareas",
        TextKey::SwitchTo => "&Cambiar a",
        TextKey::EndTask => "&Finalizar tarea",
        TextKey::EndProcess => "&Finalizar proceso",
        TextKey::Debug => "&Depurar",
        TextKey::SetPriority => "Establecer &prioridad",
        TextKey::Realtime => "&Tiempo real",
        TextKey::SetAffinity => "Establecer a&finidad...",
        TextKey::GoToProcess => "&Ir al proceso",
        TextKey::ShowFullAccountName => "Mostrar nombre completo de la cuenta",
        TextKey::SendMessageTitle => "Enviar mensaje",
        TextKey::MessageTitleLabel => "Título del mensaje:",
        TextKey::MessageLabel => "Mensaje:",
        TextKey::Disconnect => "&Desconectar",
        TextKey::Logoff => "Ce&rrar sesión",
        TextKey::SendMessage => "&Enviar mensaje...",
        TextKey::TaskManager => "Administrador de tareas",
        TextKey::Tasks => "Aplicaciones",
        TextKey::Processes => "Procesos",
        TextKey::Users => "Usuarios",
        TextKey::Handles => "Handles",
        TextKey::Threads => "Hilos",
        TextKey::ProcessesLabel => "Procesos",
        TextKey::User => "Usuario",
        TextKey::Ok => "Aceptar",
        TextKey::Cancel => "Cancelar",
        TextKey::ImageName => "Nombre de imagen",
        TextKey::PidProcessIdentifier => "PID (identificador de proceso)",
        TextKey::CpuUsage => "Uso de CPU",
        TextKey::CpuUsageHistory => "Historial de uso de CPU",
        TextKey::PhysicalMemoryK => "Memoria física (K)",
        TextKey::CommitChargeK => "Memoria confirmada (K)",
        TextKey::KernelMemoryK => "Memoria del núcleo (K)",
        TextKey::Totals => "Totales",
        TextKey::Total => "Total",
        TextKey::Available => "Disponible",
        TextKey::FileCache => "Caché de archivos",
        TextKey::Paged => "Paginado",
        TextKey::Nonpaged => "No paginado",
        TextKey::Limit => "Límite",
        TextKey::Peak => "Pico",
        TextKey::UserName => "Nombre de usuario",
        TextKey::SessionId => "Id. de sesión",
        TextKey::CpuTime => "Tiempo de CPU",
        TextKey::MemoryUsage => "Uso de memoria",
        TextKey::MemoryUsageDelta => "Delta de uso de memoria",
        TextKey::PageFaults => "Errores de página",
        TextKey::PageFaultsDelta => "Delta de errores de página",
        TextKey::VirtualMemorySize => "Tamaño de memoria virtual",
        TextKey::PagedPool => "Bloque paginado",
        TextKey::NonPagedPool => "Bloque no paginado",
        TextKey::BasePriority => "Prioridad base",
        TextKey::HandleCount => "Número de handles",
        TextKey::ThreadCount => "Número de hilos",
        TextKey::ProcessorAffinity => "Afinidad del procesador",
        TextKey::Processors => "Procesadores",
        TextKey::ClientName => "Nombre del cliente",
        TextKey::Session => "Sesión",
        TextKey::Status => "Estado",
        TextKey::Bitness32Suffix => "(32 bits)",
        TextKey::NotResponding => "No responde",
        TextKey::Running => "En ejecucion",
        TextKey::MessageCouldNotBeSent => "No se pudo enviar el mensaje.",
        TextKey::ConfirmLogoffSelectedUsers => {
            "¿Seguro que desea cerrar la sesion de los usuarios seleccionados?"
        }
        TextKey::ConfirmDisconnectSelectedUsers => {
            "¿Seguro que desea desconectar a los usuarios seleccionados?"
        }
        TextKey::SelectedUserCouldNotBeLoggedOff => {
            "No se pudo cerrar la sesion del usuario seleccionado."
        }
        TextKey::SelectedUserCouldNotBeDisconnected => {
            "No se pudo desconectar al usuario seleccionado."
        }
        TextKey::Win32ErrorPrefix => "Error de Win32:",
        TextKey::ProcessorAffinityDescription => {
            "La configuracion de afinidad del procesador controla en que CPU se permitira ejecutar el proceso."
        }
        TextKey::MemUsage => "Uso de memoria",
        TextKey::MemoryUsageHistory => "Historial de uso de memoria",
        TextKey::NoActiveNetworkAdaptersFound => "No se encontraron adaptadores de red activos.",
        TextKey::Adapter => "Adaptador",
        TextKey::NetworkUtilization => "Utilizacion de red",
        TextKey::LinkSpeed => "Velocidad del vinculo",
        TextKey::State => "Estado",
        TextKey::BytesSent => "Bytes enviados",
        TextKey::BytesReceived => "Bytes recibidos",
        TextKey::BytesTotal => "Bytes totales",
        TextKey::Recv => "Rec.",
        TextKey::Sent => "Env.",
        TextKey::Connected => "Conectado",
        TextKey::Disconnected => "Desconectado",
        TextKey::Connecting => "Conectando",
        TextKey::Disconnecting => "Desconectando",
        TextKey::HardwareMissing => "Hardware ausente",
        TextKey::HardwareDisabled => "Hardware deshabilitado",
        TextKey::HardwareMalfunction => "Fallo de hardware",
        TextKey::Unknown => "Desconocido",
        TextKey::Active => "Activo",
        TextKey::ConnectQuery => "Consulta de conexión",
        TextKey::Shadow => "Sombra",
        TextKey::Idle => "Inactivo",
        TextKey::Listening => "Escuchando",
        TextKey::Reset => "Restablecer",
        TextKey::Down => "Inactivo",
        TextKey::Init => "Inicializando",
    }
}
