//! 俄语语言表。

use super::text_key::TextKey;
use crate::resource::*;

pub fn resource(id: u32) -> &'static str {
    match id {
        IDS_PERFPAGETITLE => "Быстродействие",
        IDS_NETPAGETITLE => "Сеть",
        IDS_RUNTITLE => "Выполнить",
        IDS_RUNTEXT => "Введите имя программы, папки, документа или интернет-ресурса, и Windows откроет его.",
        IDS_APPTITLE | IDS_TASKMGR => "Диспетчер задач Windows NT",
        IDS_PROCPAGETITLE => "Процессы",
        IDS_TASKPAGETITLE => "Приложения",
        IDS_USERPAGETITLE => "Пользователи",
        IDS_TASKMGRDISABLED => "Диспетчер задач отключен администратором.",
        IDS_WARNING => "Предупреждение диспетчера задач",
        IDS_LOW => "Низкий",
        IDS_HIGH => "Высокий",
        IDS_REALTIME => "Реального времени",
        IDS_NORMAL => "Обычный",
        IDS_UNKNOWN => "Неизвестно",
        IDS_CANTSETAFFINITY => "Не удалось выполнить операцию.\n\n",
        IDS_CANTKILL => "Не удалось завершить процесс",
        IDS_CANTDEBUG => "Не удалось подключить отладчик",
        IDS_CANTCHANGEPRI => "Не удалось изменить приоритет",
        IDS_FMTTASKS => "Приложения: %d",
        IDS_FMTPROCS => "Процессы: %d",
        IDS_FMTCPU => "Загрузка CPU: %d%%",
        IDS_FMTMEM => "Использование памяти: %dK / %dK",
        IDS_INVALIDOPTION => "Недопустимый параметр",
        IDS_NOAFFINITYMASK => "Процесс должен иметь привязку как минимум к одному процессору.",
        IDS_FMTCPUNUM => "CPU %d",
        IDS_TOTALTIME => "Общий CPU",
        IDS_KERNELTIME => "CPU ядра",
        IDS_MEMUSAGE => "Использование памяти",
        IDS_COL_IMAGENAME => "Имя образа",
        IDS_COL_PID => "PID",
        IDS_COL_CPU => "CPU",
        IDS_COL_CPUTIME => "Время CPU",
        IDS_COL_MEMUSAGE => "Использование памяти",
        IDS_COL_MEMUSAGEDIFF => "Изменение памяти",
        IDS_COL_PAGEFAULTS => "Ошибки страниц",
        IDS_COL_PAGEFAULTSDIFF => "Изменение ошибок страниц",
        IDS_COL_COMMITCHARGE => "Размер виртуальной памяти",
        IDS_COL_PAGEDPOOL => "Выгружаемый пул",
        IDS_COL_NONPAGEDPOOL => "Невыгружаемый пул",
        IDS_COL_BASEPRIORITY => "Базовый приоритет",
        IDS_COL_HANDLECOUNT => "Дескрипторы",
        IDS_COL_THREADCOUNT => "Потоки",
        IDS_COL_SESSIONID => "ID сеанса",
        IDS_COL_USERNAME => "Имя пользователя",
        IDS_COL_TASKNAME => "Задача",
        IDS_COL_TASKSTATUS => "Состояние",
        IDS_COL_TASKWINSTATION => "Станция Win",
        IDS_COL_TASKDESKTOP => "Рабочий стол",
        IDS_PRICHANGE => {
            "ПРЕДУПРЕЖДЕНИЕ: изменение класса приоритета этого процесса может привести к нежелательным последствиям, включая нестабильность системы. Вы действительно хотите изменить класс приоритета?"
        }
        IDS_KILL => {
            "ПРЕДУПРЕЖДЕНИЕ: завершение процесса может привести к нежелательным последствиям, включая потерю данных и нестабильность системы. Перед завершением процесс не сможет сохранить свое состояние или данные. Вы действительно хотите завершить этот процесс?"
        }
        IDS_DEBUG => {
            "ПРЕДУПРЕЖДЕНИЕ: отладка этого процесса может привести к потере данных. Вы действительно хотите подключить отладчик?"
        }
        _ => "",
    }
}

pub fn text(key: TextKey) -> &'static str {
    match key {
        TextKey::File => "&Файл",
        TextKey::Options => "&Параметры",
        TextKey::View => "&Вид",
        TextKey::Windows => "&Окна",
        TextKey::Help => "&Справка",
        TextKey::UpdateSpeed => "&Скорость обновления",
        TextKey::CpuHistory => "&Журнал CPU",
        TextKey::SelectColumnsMenu => "Выбрать столбцы...",
        TextKey::SelectColumnsTitle => "Выбор столбцов",
        TextKey::SelectProcessColumnsDescription => {
            "Выберите столбцы, которые будут отображаться на вкладке Процессы диспетчера задач."
        }
        TextKey::NewTaskMenu | TextKey::NewTaskButton => "&Выполнить...",
        TextKey::ExitTaskManager => "&Выход из диспетчера задач",
        TextKey::AlwaysOnTop => "&Поверх всех окон",
        TextKey::MinimizeOnUse => "&Сворачивать после использования",
        TextKey::Confirmations => "&Подтверждения",
        TextKey::HideWhenMinimized => "&Скрывать при сворачивании",
        TextKey::RefreshNow => "&Обновить",
        TextKey::High => "&Высокая",
        TextKey::Normal => "&Обычная",
        TextKey::Low => "&Низкая",
        TextKey::Paused => "&Пауза",
        TextKey::LargeIcons => "&Крупные значки",
        TextKey::SmallIcons => "&Мелкие значки",
        TextKey::Details => "&Подробности",
        TextKey::TileHorizontally => "Расположить &горизонтально",
        TextKey::TileVertically => "Расположить &вертикально",
        TextKey::Minimize => "&Свернуть",
        TextKey::Maximize => "Ра&звернуть",
        TextKey::Cascade => "&Каскадом",
        TextKey::BringToFront => "На &передний план",
        TextKey::HelpTopics => "&Разделы справки диспетчера задач",
        TextKey::AboutTaskManager => "&О диспетчере задач",
        TextKey::OneGraphAllCpus => "Один график, &все CPU",
        TextKey::OneGraphPerCpu => "Один график &на CPU",
        TextKey::ShowKernelTimes => "Показывать время &ядра",
        TextKey::NoTitle => "&Без заголовка",
        TextKey::RestoreTaskManager => "&Восстановить диспетчер задач",
        TextKey::SwitchTo => "Пере&ключить",
        TextKey::EndTask => "&Снять задачу",
        TextKey::EndProcess => "&Завершить процесс",
        TextKey::Debug => "&Отладка",
        TextKey::SetPriority => "Задать &приоритет",
        TextKey::Realtime => "&Реального времени",
        TextKey::SetAffinity => "Задать &привязку...",
        TextKey::GoToProcess => "&Перейти к процессу",
        TextKey::ShowFullAccountName => "Показывать полное имя учетной записи",
        TextKey::SendMessageTitle => "Отправить сообщение",
        TextKey::MessageTitleLabel => "Заголовок сообщения:",
        TextKey::MessageLabel => "Сообщение:",
        TextKey::Disconnect => "&Отключить",
        TextKey::Logoff => "&Выход из системы",
        TextKey::SendMessage => "&Отправить сообщение...",
        TextKey::TaskManager => "Диспетчер задач",
        TextKey::Tasks => "Приложения",
        TextKey::Processes => "Процессы",
        TextKey::Users => "Пользователи",
        TextKey::Handles => "Дескрипторы",
        TextKey::Threads => "Потоки",
        TextKey::ProcessesLabel => "Процессы",
        TextKey::User => "Пользователь",
        TextKey::Ok => "OK",
        TextKey::Cancel => "Отмена",
        TextKey::ImageName => "Имя образа",
        TextKey::PidProcessIdentifier => "PID (идентификатор процесса)",
        TextKey::CpuUsage => "Загрузка CPU",
        TextKey::CpuUsageHistory => "Журнал загрузки CPU",
        TextKey::PhysicalMemoryK => "Физическая память (K)",
        TextKey::CommitChargeK => "Выделенная память (K)",
        TextKey::KernelMemoryK => "Память ядра (K)",
        TextKey::Totals => "Итоги",
        TextKey::Total => "Всего",
        TextKey::Available => "Доступно",
        TextKey::FileCache => "Файловый кэш",
        TextKey::Paged => "Выгружаемая",
        TextKey::Nonpaged => "Невыгружаемая",
        TextKey::Limit => "Предел",
        TextKey::Peak => "Пик",
        TextKey::UserName => "Имя пользователя",
        TextKey::SessionId => "ID сеанса",
        TextKey::CpuTime => "Время CPU",
        TextKey::MemoryUsage => "Использование памяти",
        TextKey::MemoryUsageDelta => "Изменение использования памяти",
        TextKey::PageFaults => "Ошибки страниц",
        TextKey::PageFaultsDelta => "Изменение ошибок страниц",
        TextKey::VirtualMemorySize => "Размер виртуальной памяти",
        TextKey::PagedPool => "Выгружаемый пул",
        TextKey::NonPagedPool => "Невыгружаемый пул",
        TextKey::BasePriority => "Базовый приоритет",
        TextKey::HandleCount => "Число дескрипторов",
        TextKey::ThreadCount => "Число потоков",
        TextKey::ProcessorAffinity => "Привязка процессора",
        TextKey::Processors => "Процессоры",
        TextKey::Status => "Состояние",
        TextKey::ClientName => "Имя клиента",
        TextKey::Session => "Сеанс",
        TextKey::Bitness32Suffix => "(32-разрядный)",
        TextKey::NotResponding => "Не отвечает",
        TextKey::Running => "Работает",
        TextKey::MessageCouldNotBeSent => "Сообщение не удалось отправить.",
        TextKey::ConfirmLogoffSelectedUsers => {
            "Вы действительно хотите завершить сеанс выбранных пользователей?"
        }
        TextKey::ConfirmDisconnectSelectedUsers => {
            "Вы действительно хотите отключить выбранных пользователей?"
        }
        TextKey::SelectedUserCouldNotBeLoggedOff => {
            "Не удалось завершить сеанс выбранного пользователя."
        }
        TextKey::SelectedUserCouldNotBeDisconnected => {
            "Не удалось отключить выбранного пользователя."
        }
        TextKey::Win32ErrorPrefix => "Ошибка Win32:",
        TextKey::ProcessorAffinityDescription => {
            "Параметр привязки процессора определяет, на каких CPU разрешено выполняться процессу."
        }
        TextKey::MemUsage => "Использование памяти",
        TextKey::MemoryUsageHistory => "История использования памяти",
        TextKey::NoActiveNetworkAdaptersFound => "Активные сетевые адаптеры не найдены.",
        TextKey::Adapter => "Адаптер",
        TextKey::NetworkUtilization => "Использование сети",
        TextKey::LinkSpeed => "Скорость канала",
        TextKey::State => "Состояние",
        TextKey::BytesSent => "Отправлено байт",
        TextKey::BytesReceived => "Получено байт",
        TextKey::BytesTotal => "Всего байт",
        TextKey::Recv => "Принято",
        TextKey::Sent => "Отпр.",
        TextKey::Connected => "Подключено",
        TextKey::Disconnected => "Отключено",
        TextKey::Connecting => "Подключение",
        TextKey::Disconnecting => "Отключение",
        TextKey::HardwareMissing => "Оборудование отсутствует",
        TextKey::HardwareDisabled => "Оборудование отключено",
        TextKey::HardwareMalfunction => "Сбой оборудования",
        TextKey::Unknown => "Неизвестно",
        TextKey::Active => "Активно",
        TextKey::ConnectQuery => "Запрос подключения",
        TextKey::Shadow => "Теневая",
        TextKey::Idle => "Ожидание",
        TextKey::Listening => "Ожидание подключения",
        TextKey::Reset => "Сброс",
        TextKey::Down => "Отключено",
        TextKey::Init => "Инициализация",
    }
}
